jetkvm/kvm

- ui/package-lock.json
- ui/package.json
Bump the react-icons NPM package to solve missing `LuEllipsisVertical` icon.
> Fix: Update react-icons package

- .devcontainer/devcontainer.json
- Makefile
- dev_deploy.sh
Adds a devcontainer configuration with golang and nodejs support. Also updates `./dev_deploy.sh` to not require a python http server, making it easier to deploy from within a container network environment. 
This was tested on my JetKVM device, but a second round of validation wouldn't hurt.
> chore: Add devcontainer support

- web.go
Don't allow empty tokens in the protected Middleware.
> Fix: Don't allow empty tokens

- cloud.go
- go.mod
- go.sum
This PR replaces the cloud-service WebSocket dependency `nhooyr.io/websocket` with `github.com/coder/websocket` which is the same library, but is actively maintained by Coder.
Also bumps the library to 1.8.12 which is compatible.
> chore: use github.com/coder/websocket instead of nhooyr.io/websocket

- cloud.go
- main.go
This PR only starts the WebSocket client loop if a token was set in `config.CloudToken` at start time, it also starts the loop if the adoption process runs after the fact.
This avoids your log being full of `Websocket client error: cloud token is not set` while working on the application, and stops the loop pointlessly running.
> fix(cloud): only start WS Client if config.CloudToken is set

- native.go
Noticed while developing if the main process crashes than the native subprocess orphans. Not and issue during normal operation since the watchdog just restarts the device, but during development and running things through ssh this makes it a little annoying.
> fix: Clean up native subprocess if main process dies

- ui/src/components/MountMediaDialog.tsx
* Fedora 38 is EOL, bump to 41 and use main Fedora mirror
* Bumps Arch Linux and Debian to latest builds
> Update to latest ISO versions

- ui/src/components/WebRTCVideo.tsx
Fixes #70 by just removing it all together, with a preference towards usability over appearance allowing the user to see the corners without using fullscreen mode
> Remove rounded corners from video stream

- ui/package.json
- ui/src/components/ActionBar.tsx
- ui/src/components/WebRTCVideo.tsx
- ui/vite.config.ts
Fixes #21 
Updates the absolute mouse position calculation to take into account differing aspect ratio between the video element and the video stream, which happens when fullscreening the screen share.
This also adds `dev:device` package.json script to allow doing live-reload against a development JetKVM device. As introduced in #10
> Fix fullscreen video absolute position

- config.go
- jsonrpc.go
- native.go
This pull request fixes #33 by introducing a new config entry `EdidString` and saves the EDID string to it when it's modified in the frontend.
This PR also introduces a method to restore the EDID on reboot/app restart by sending the `EdidString` back to jetkvm_native when it connects to the control socket.
> feat: restore EDID on reboot

- network.go
This PR fixes #12 by placing the `udhcpc` DHCP client into an idle state when the network interface goes link down.
When the link transitions down, this PR will:
- Send `udhcpc` the `USR2` signal which puts it into an idle state <sup>1</sup>
- Remove all IPv4 addresses from the interface
Then once the interface comes back up, it'll send `USR1` to `udhcpc` which activates it and forces it to get a new lease.
This not only fixes the issue reported in #12 by removing the active addresses, it ensures that if the JetKVM is moved to a new subnet, it'll get an IPv4 address from the DHCP server on the new network, rather than trying to hold on to a dead lease from the previous network.
I'd like some feedback on the implementation of this, as it's just invoking the `killall` command with the …
> fix(network.go): fix stuck IPv4 addresses on linkstate cycle

- network.go
mDNS is started before network is 'up'. When this happens, it fails to bind and never listens to connections.
To resolve this, restart mDNS every time the network state changes. Restarting the server will also catch any addresses which may have changed since the server was last started, so we cannot do this only on up/down changes, but any address change.
Resolves #140
> Restart mDNS every time the connection information changes

- config.go
- display.go
- jsonrpc.go
- native.go
- web.go
Also removed unnecessary `loadConfig()`
> chore(config): merge userConfig with defaultConfig and add a lock

- .devcontainer/devcontainer.json
This setting is needed to run `dev_deploy.sh` successfully.  If you are developing inside of the container the container doesn't have any ssh keys and falls back to password auth.  This setting maps your keys local to the container so the deploy to device will work.
> fix(devcontainer): Map local ssh keys to container

- ui/src/components/MountMediaDialog.tsx
The previous URL no longer works because the noble folder replaces old version files with new ones.
> fix(ui): Fix & Update Ubuntu 24.04 LTS ISO download URL to latest

- cloud.go
- config.go
- jsonrpc.go
- ui/.env.device
- ui/src/components/USBConfigDialog.tsx
- ui/src/main.tsx
- ui/src/routes/adopt.tsx
- ui/src/routes/devices.$id.settings.access._index.tsx
- ui/src/ui.config.ts
- web.go
- Removes all environment variables building in `device` mode
- Add Cloud app url to device config
- Simplifies using alternative cloud providers
cc @timothystewart6
> feat(cloud): Add support for custom cloud app URL configuration

- Makefile
> fix(build): Fix Buildate date

- jsonrpc.go
Fixes #102
udc would always be empty/null on initalise so udcFilePath would check the wrong file/folder
> fix rpcGetUsbEmulationState filepath

- ui/src/routes/devices.$id.mount.tsx
Fixes #234 
adds a simple confirm prompt box, so you dont delete iso's by mistake
> add confirm prompt to delete file

- block_device.go
- usb_mass_storage.go
* Cleanup additional `fmt.Println()` that should call logger.
* Use `%v` for logging errors.
> fix: Logging cleanup

- ui/src/components/WebRTCVideo.tsx
- ui/src/routes/devices.$id.tsx
The current error handling implementation assumes that the PeerConnection will declare failure when the user has an issue establishing a connection. This is not the case, often the PeerConnection will be "Connecting" forever.
This results in that the user never sees the Connection Error modal. This PR, implements a proper failure after either 30 connection attempts or 60s of time. After that, we show the Connection Error modal. 
The failures thresholds can be changed, but I started with a rather large retry limit and long timeout.
> Improve connection error handling

- .golangci.yml
- prometheus.go
- serial.go
- web.go
- web_tls.go
Enable more golangci-lint linters.
* `forbidigo` to stop use of non-logger console printing.
* `goimports` to make sure `import` blocks are formatted nicely.
* `misspell` to catch spelling mistakes.
* `whitespace` to catch whitespace issues.
> chore: Enable more linters

- README.md
Corrects Discord link in the help section, reported in #306
> chore: Update README Discord Link

- ui/src/components/Header.tsx
- ui/src/components/USBStateStatus.tsx
- ui/src/components/VideoOverlay.tsx
- ui/src/components/WebRTCVideo.tsx
- ui/src/routes/devices.$id.other-session.tsx
- ui/src/routes/devices.$id.tsx
This PR makes the WebRTC flow much clearer. The new approach is fail-and-retry locally, if retries fail - stop everything and let the user retry themselves.
- Added `LoadingConnectionOverlay` to provide better user feedback during connection attempts.
- Replaced generic retry logic with targeted failure conditions.
> refactor: Update WebRTC connection handling and overlays

- ota.go
Fixes https://github.com/jetkvm/kvm/issues/258 , though not neatly.
> chore(ota): allow a longer timeout when downloading packages

- dev_deploy.sh
- publish_source.sh
- ui/dev_device.sh
Cleanup various shell linting issues
* Use `/usr/bin/env` consistently for better platform compatibility.
* SC2317 (info): Command appears to be unreachable.
* SC2002 (style): Useless cat.
> fix: Shell linting

- ui/src/components/VideoOverlay.tsx
THe sentence was incomplete without "ensure".
> VideoOverlay: add missing word to adapter line

- config.go
- display.go
- jsonrpc.go
- ui/src/hooks/stores.ts
- ui/src/routes/devices.$id.settings.hardware.tsx
This PR adds the UI for changing display orientation.
This PR _does not_ include an updated `jetkvm_native`. In order to test this PR, compile the binary based on https://github.com/jetkvm/jetkvm-native/pull/3 and copy it to `resource`.
Fixes https://github.com/jetkvm/kvm/issues/124
Partly fixes https://github.com/jetkvm/kvm/issues/43 (only rotation)
> UI for changing display orientation

- internal/usbgadget/hid_mouse_absolute.go
This defect was discovered in #182 and should address the issue there as well as #317 and #358.
Between @rmschooley and me, we narrowed the issue down to the /dev/hidg1 device, and @rmschooley suggested this change to the HID descriptor, which in my testing successfully resolved the erratic scrolling behaviour.
> Fix mouse scrolling issues

- internal/timesync/ntp.go
This PR addresses two issues in the NTP time sync logic:
1. Fix panic on query error
Previously, if `queryNtpServer` failed, `jetkvm_app` would panic at startup due to unchecked errors. This has been fixed by adding proper error handling before using the response.
2. Support IPv6-only environments
The default NTP server list included only hostnames or IPv4 addresses, which fail in pure IPv6 setups—especially since IPv6 RA RDNSS is not yet supported, preventing hostname resolution. This PR adds a known IPv6-accessible NTP server to defaultNTPServers to ensure compatibility in such environments.
> ntp: fix panic on NTP query error and add IPv6 server for IPv6-only support

- ui/src/components/WebRTCVideo.tsx
- ui/src/keyboardMappings.ts
This PR fixes the Alt Graph key not being recognized.
Provides fixes for #30, #118, #313.
This can be tested by adding following log statements to `internal/usbgadget/hid_keyboard.go`:
```golang
func (u *UsbGadget) keyboardWriteHidFile(data []byte) error {
if u.keyboardHidFile == nil {
var err error
u.keyboardHidFile, err = os.OpenFile("/dev/hidg0", os.O_RDWR, 0666)
if err != nil {
return fmt.Errorf("failed to open hidg0: %w", err)
}
}
fmt.Println("-- hid_keyboard --")
fmt.Printf("modf: 0x%x\n", data[0])
fmt.Printf("key1: 0x%x\n", data[2])
fmt.Printf("key2: 0x%x\n", data[3])
fmt.Printf("key3: 0x%x\n", data[4])
fmt.Printf("key4: 0x%x\n", data[5])
fmt.Printf("key5: 0x%x\n", data[6])
fmt.Printf("key6: 0x%x\n", data[7])
fmt.Println("------------------")
_, err := u.keyboardHidFile.Write(data) …
```
> Fix: Alt Gr not recognized

- dev_deploy.sh
Adds `--reset-usb-hid` command to delete the configured USB HID device before running.
Fixes #438
> feat: Reset optionally reset USB HID in dev-deploy

- ui/src/components/VirtualKeyboard.tsx
- ui/src/keyboardMappings.ts
Fix the display problems with shifted keys (should show capitals and symbols, but was showing (KeyX) and the state management was losing the Shift modifer.
Add the missing keys from the directional keys section, added Insert, added Print Screen/System Request, added Scroll Lock, added Pause/Break. Fixed display for the Delete key.
Added (but not exposed on normal US keyboard yet) the Numpad Equal
Builds on #447
> feat(ui): Enhance Virtual Keyboard for US

- .devcontainer/devcontainer.json
Missed that we upgraded the ui's package.json, need to _also_ update the devcontainer.json to matching verison 22.15.0
> chore: Update devcontainer.json to match ui's package.json

- internal/usbgadget/hid_mouse_absolute.go
- internal/usbgadget/utils.go
- ui/src/components/WebRTCVideo.tsx
This pull request makes several small but significant changes to the mouse wheel scroll behavior. In addition to guaranteeing that every mouse wheel click produces a scroll, these changes also maintain most if not all of the acceleration scroll values provided by many popular browsers. These changes simplify the code and make the various user scroll sensitivity settings completely unnecessary. However, these settings were not removed in this request.
These changes have been tested under the following environments. Unless otherwise noted, the scrolling behavior seems to work perfectly fine in these environments.
1. Windows 10 - Chrome 136 - Mouse (Delta = 100)
2. Windows 10 - Edge 136 - Mouse (Delta = 100)
3. Windows 10 - Firefox 138 - Mouse (Delta = 108)
4. Windows 10 - Opera 119 - Mouse …
> Improve/Simplify Mouse Wheel Scroll Behavior

- ui/src/components/popovers/PasteModal.tsx
- ui/src/routes/devices.$id.settings.keyboard.tsx
The recent fix to PasteModal will silently fail a paste if the keyboardLayout hasn't been selected in the settings yet, then when you look in Settings it looks like it's set to Belgian, but it's really just blank. Set it to default to en-US in both these places so it works like it did previously.
Fixes #492
> fix(ui): Default the keyboardLayout to en-US if not set

- .devcontainer/devcontainer.json
- .vscode/settings.json
Adds a set of common extensions to the `.devcontainer` that are pretty useful for Typescript (+tailwind) & Go
> chore: add VSCode extensions for improved development environment

- ui/src/components/InfoBar.tsx
- ui/src/hooks/stores.ts
- ui/src/routes/devices.$id.settings.keyboard.tsx
The User can activate or deactivate the display of pressed keys in the status-bar of the interface by toggling the checkbox in the keyboard settings menu.
> feat(Keyboard): Hide Pressed Keys (Option to hide key event shown on status bar #365)

- ui/src/hooks/stores.ts
Now that we don't do any mouse/trackpad sensitivity settings, this whole interface is unused.
> chore(ui): Removed unused DeviceSettingState

- display.go
- internal/udhcpc/udhcpc.go
Fix for #531
Remove the unnecessary defer ticker stops. Also ensure that we don't process the lease multiple times if it has not changed since it wakes the device up every time.
> Fix for #531 - The screen doesn't dim or turn off

- ui/src/components/WebRTCVideo.tsx
- ui/src/hooks/stores.ts
- ui/src/routes/devices.$id.settings.mouse.tsx
I know it's a bit of a controversial topic, but I feel as though the recently removed scroll sensitivity options were actually helpful on some devices.
Particularly as a Mac user, I think the wheel event blocking/throttling really helped tone down the scrolling speed.
This PR (re)introduces just the blocking/throttling mechanism to prevent excessive scroll events from being sent to the host system.
Given not everyone is convinced this actually makes any difference, an "Off" setting is available to maintain today's existing behaviour. This is the default setting.
For me, On my Macbook I like the "Medium" or "High" options -- depending on what I'm working on.
As always, criticism is welcome!
> scroll throttling preference

- cloud.go
- internal/timesync/metrics.go
Fix up metric names to follow best practice naming conventions[0].
[0]: https://prometheus.io/docs/practices/naming/
> fix: Update metric naming

- internal/timesync/http.go
Fixes https://github.com/jetkvm/kvm/issues/576
A temporary workaround before the next release would be to disable HTTP sync.
> fix(timesync): queryMultipleHttp hanging if all servers are unreachable
